var groups = [{
    "name": "Мультимедийная техника",
    "items": [{
      "name": "Телефоны б,у",
      "max": "4 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }]
    }, {
      "name": "Телефоны новые",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }]
    }, {
      "name": "Телефоны новые",
      "max": "2ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }]
    }, {
      "name": "Фотоаппараты  и камеры с креплением",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }]
    }, {
      "name": "Роутеры",
      "max": "5 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }]
    }, {
      "name": "Электроный Блок управления или компьютер-монитор",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 1800
      }]
    }, {
      "name": "Кабеля любые и др комлект",
      "max": "до 1 бабины",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 1800
      }]
    }, {
      "name": "Веб-камеры",
      "max": "5 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }]
    }, {
      "name": "Ноутбуки",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }]
    }, {
      "name": "Планшеты",
      "max": "2 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }]
    }, {
      "name": "Сист. Блок   б/у или корпус",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 1800
      }]
    }, {
      "name": "Сист. Блок  новый в сборе",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 1800
      }]
    }, {
      "name": "Материн и др платы в коробках",
      "max": "2 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }]
    }, {
      "name": "Переферия и аксесуары (мыши, клавиатуры, наушники…)",
      "max": "20 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }]
    }, {
      "name": "Мониторы",
      "max": "2 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 1800
      }]
    }, {
      "name": "(принтер, сканер)",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 1800
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": 2200
      }, {
        "from": 35,
        "to": 40,
        "price": 2400
      }]
    }, {
      "name": "Сборная мультимедийная техника в кол-ве не более по 1 ед. каждого",
      "max": "15 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1400
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 1800
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": 2200
      }, {
        "from": 35,
        "to": 40,
        "price": 2400
      }]
    }, {
      "name": "Процессор, оперативная памть, накопители.",
      "max": "5 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 400
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 800
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }]
    }]
  },
  {
    "name": "Телевизоры",
    "items": [{
      "name": "Телевизоры  до 55",
      "max": "1ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 300
      }, {
        "from": 1,
        "to": 2,
        "price": 300
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 400
      }, {
        "from": 10,
        "to": 15,
        "price": 600
      }, {
        "from": 15,
        "to": 20,
        "price": 800
      }, {
        "from": 20,
        "to": 25,
        "price": 1000
      }, {
        "from": 25,
        "to": 30,
        "price": 1200
      }, {
        "from": 30,
        "to": 35,
        "price": 1400
      }, {
        "from": 35,
        "to": 40,
        "price": 1800
      }]
    }]
  },
  {
    "name": "Бытовая техника",
    "items": [{
      "name": "Микроволн",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1100
      }, {
        "from": 20,
        "to": 25,
        "price": 1300
      }, {
        "from": 25,
        "to": 30,
        "price": 1000
      }, {
        "from": 30,
        "to": 35,
        "price": 1200
      }, {
        "from": 35,
        "to": 40,
        "price": 1400
      }]
    }, {
      "name": "Пылесос",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1100
      }, {
        "from": 20,
        "to": 25,
        "price": 1300
      }, {
        "from": 25,
        "to": 30,
        "price": 1000
      }, {
        "from": 30,
        "to": 35,
        "price": 1200
      }, {
        "from": 35,
        "to": 40,
        "price": 1400
      }]
    }, {
      "name": "Эл.Чайники и др нагреватели",
      "max": "2 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1100
      }, {
        "from": 20,
        "to": 25,
        "price": 1300
      }, {
        "from": 25,
        "to": 30,
        "price": 1000
      }, {
        "from": 30,
        "to": 35,
        "price": 1200
      }, {
        "from": 35,
        "to": 40,
        "price": 1400
      }]
    }, {
      "name": "Блендеры-миксеры-тестомесилки",
      "max": "2 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1100
      }, {
        "from": 20,
        "to": 25,
        "price": 1300
      }, {
        "from": 25,
        "to": 30,
        "price": 1000
      }, {
        "from": 30,
        "to": 35,
        "price": 1200
      }, {
        "from": 35,
        "to": 40,
        "price": 1400
      }]
    }, {
      "name": "Хлебопечки",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1100
      }, {
        "from": 20,
        "to": 25,
        "price": 1300
      }, {
        "from": 25,
        "to": 30,
        "price": 1000
      }, {
        "from": 30,
        "to": 35,
        "price": 1200
      }, {
        "from": 35,
        "to": 40,
        "price": 1400
      }]
    }, {
      "name": "Мультиварки",
      "max": "2ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1100
      }, {
        "from": 20,
        "to": 25,
        "price": 1300
      }, {
        "from": 25,
        "to": 30,
        "price": 1000
      }, {
        "from": 30,
        "to": 35,
        "price": 1200
      }, {
        "from": 35,
        "to": 40,
        "price": 1400
      }]
    }, {
      "name": "Фены и др мелк эл техника",
      "max": "2 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1100
      }]
    }, {
      "name": "Сборная  бытовая техника в кол-ве не более по 1 ед. каждого",
      "max": "7 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1100
      }, {
        "from": 20,
        "to": 25,
        "price": 1300
      }]
    }]
  },
  {
    "name": "Крупная бытовая техника",
    "items": [{
      "name": "Кондиционеры, Бойлеры, Газ. Колонки,Вытяжки, настол газ плиты",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 300
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }, {
        "from": 20,
        "to": 25,
        "price": 1500
      }, {
        "from": 25,
        "to": 30,
        "price": 1500
      }, {
        "from": 30,
        "to": 35,
        "price": 2000
      }, {
        "from": 35,
        "to": 40,
        "price": 2500
      }]
    }, {
      "name": "Холодильники, Стиральные машины, Газовые плиты, 2х контр котлы и др",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 300
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }, {
        "from": 20,
        "to": 25,
        "price": 1500
      }, {
        "from": 25,
        "to": 30,
        "price": 1500
      }, {
        "from": 30,
        "to": 35,
        "price": 2000
      }, {
        "from": 35,
        "to": 40,
        "price": 2500
      }]
    }, {
      "name": "Музыкальные инструменты",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 300
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }, {
        "from": 20,
        "to": 25,
        "price": 1500
      }, {
        "from": 25,
        "to": 30,
        "price": 1500
      }, {
        "from": 30,
        "to": 35,
        "price": 2000
      }, {
        "from": 35,
        "to": 40,
        "price": 2500
      }]
    }]
  },
  {
    "name": "Мебель и другие  домашние приборы",
    "items": [{
      "name": "Столы и стулья разобранные и Тренажеры, велосипеды, басейны и тд",
      "max": "1 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 50
      }, {
        "from": 4,
        "to": 5,
        "price": 50
      }, {
        "from": 5,
        "to": 10,
        "price": 100
      }, {
        "from": 10,
        "to": 15,
        "price": 300
      }, {
        "from": 15,
        "to": 20,
        "price": 400
      }, {
        "from": 20,
        "to": 25,
        "price": 500
      }, {
        "from": 25,
        "to": 30,
        "price": 600
      }, {
        "from": 30,
        "to": 35,
        "price": 700
      }, {
        "from": 35,
        "to": 40,
        "price": 800
      }]
    }, {
      "name": "Электрические и механические домашние приборы( люстры, светильники, бра, часы, и тд)",
      "max": "2 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 50
      }, {
        "from": 4,
        "to": 5,
        "price": 50
      }, {
        "from": 5,
        "to": 10,
        "price": 100
      }, {
        "from": 10,
        "to": 15,
        "price": 300
      }, {
        "from": 15,
        "to": 20,
        "price": 400
      }, {
        "from": 20,
        "to": 25,
        "price": 500
      }, {
        "from": 25,
        "to": 30,
        "price": 600
      }, {
        "from": 30,
        "to": 35,
        "price": 700
      }, {
        "from": 35,
        "to": 40,
        "price": 800
      }]
    }, {
      "name": "Матрацы без пружин, подушки,ОДЕЯЛА,КОВРЫ",
      "max": "1 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 50
      }, {
        "from": 4,
        "to": 5,
        "price": 50
      }, {
        "from": 5,
        "to": 10,
        "price": 100
      }, {
        "from": 10,
        "to": 15,
        "price": 300
      }, {
        "from": 15,
        "to": 20,
        "price": 400
      }, {
        "from": 20,
        "to": 25,
        "price": 500
      }, {
        "from": 25,
        "to": 30,
        "price": 600
      }, {
        "from": 30,
        "to": 35,
        "price": 700
      }, {
        "from": 35,
        "to": 40,
        "price": 800
      }]
    }]
  },
  {
    "name": "Столовая посуда",
    "items": [{
      "name": "Посуда новая",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 200
      }, {
        "from": 10,
        "to": 15,
        "price": 300
      }, {
        "from": 15,
        "to": 20,
        "price": 800
      }, {
        "from": 20,
        "to": 25,
        "price": 1500
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": null
      }]
    }, {
      "name": "ножи турист-охота",
      "max": "2ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }]
    }, {
      "name": "Ножи бытовые",
      "max": "5 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }]
    }]
  },
  {
    "name": "Парфюмерия и косметика",
    "items": [{
      "name": "Парфюмер.  и алкоголь. наборы",
      "max": "до1л до2ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }]
    }, {
      "name": "Косметика  ",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 1000
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }]
    }]
  },
  {
    "name": "Гигиена",
    "items": [{
      "name": "Памперсы",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 100
      }, {
        "from": 3,
        "to": 4,
        "price": 100
      }, {
        "from": 4,
        "to": 5,
        "price": 100
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 1000
      }, {
        "from": 15,
        "to": 20,
        "price": 1500
      }, {
        "from": 20,
        "to": 25,
        "price": 250
      }, {
        "from": 25,
        "to": 30,
        "price": 500
      }, {
        "from": 30,
        "to": 35,
        "price": 900
      }, {
        "from": 35,
        "to": 40,
        "price": 1100
      }]
    }, {
      "name": "Средства и средства личной гигиены новое",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 100
      }, {
        "from": 3,
        "to": 4,
        "price": 100
      }, {
        "from": 4,
        "to": 5,
        "price": 100
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 1000
      }, {
        "from": 15,
        "to": 20,
        "price": 1500
      }]
    }]
  },
  {
    "name": "Питание",
    "items": [{
      "name": "Корм для животных",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 1000
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 600
      }, {
        "from": 15,
        "to": 20,
        "price": 800
      }, {
        "from": 20,
        "to": 25,
        "price": 1200
      }, {
        "from": 25,
        "to": 30,
        "price": 1400
      }, {
        "from": 30,
        "to": 35,
        "price": 1500
      }, {
        "from": 35,
        "to": 40,
        "price": 2000
      }]
    }, {
      "name": "БАДы для питания, Спорт питан",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 1000
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }]
    }, {
      "name": "Лекарства и Бады для лечения ",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 1000
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }]
    }, {
      "name": "Чай, кофе,сухарики ,чипсы, семена, и др гастроном продукты сухого хранения",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 1000
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 600
      }, {
        "from": 15,
        "to": 20,
        "price": 800
      }, {
        "from": 20,
        "to": 25,
        "price": 1200
      }, {
        "from": 25,
        "to": 30,
        "price": 1400
      }]
    }, {
      "name": "ИКРА красн / черная ",
      "max": "2 банки",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 200
      }, {
        "from": 1,
        "to": 2,
        "price": 1000
      }]
    }]
  },
  {
    "name": "Одежда новая",
    "items": [{
      "name": "Одежда( рубашки, платья, футболки, халаты) ",
      "max": "20 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }, {
        "from": 20,
        "to": 25,
        "price": 2500
      }, {
        "from": 25,
        "to": 30,
        "price": 1500
      }]
    }, {
      "name": "Одежда( пиджаки, костюмы м/ж, куртки кроме кож и зимн, брюки,юбки)",
      "max": "10 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }, {
        "from": 20,
        "to": 25,
        "price": 2500
      }, {
        "from": 25,
        "to": 30,
        "price": 1500
      }, {
        "from": 30,
        "to": 35,
        "price": 1500
      }, {
        "from": 35,
        "to": 40,
        "price": 2000
      }]
    }, {
      "name": "Одежда верхняя(пальто, куртки теплые и кожаные)",
      "max": "5 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }, {
        "from": 20,
        "to": 25,
        "price": 2500
      }, {
        "from": 25,
        "to": 30,
        "price": 1500
      }, {
        "from": 30,
        "to": 35,
        "price": 1500
      }, {
        "from": 35,
        "to": 40,
        "price": 2000
      }]
    }, {
      "name": "Одежда меховая ",
      "max": "3 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }, {
        "from": 20,
        "to": 25,
        "price": 2500
      }, {
        "from": 25,
        "to": 30,
        "price": 1500
      }, {
        "from": 30,
        "to": 35,
        "price": 1500
      }, {
        "from": 35,
        "to": 40,
        "price": 2000
      }]
    }, {
      "name": "Ткани, пленка, постельное, полотенца",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }, {
        "from": 20,
        "to": 25,
        "price": 2500
      }, {
        "from": 25,
        "to": 30,
        "price": 1500
      }, {
        "from": 30,
        "to": 35,
        "price": 1500
      }, {
        "from": 35,
        "to": 40,
        "price": 2000
      }]
    }, {
      "name": "Белье, колготки, носки",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }, {
        "from": 20,
        "to": 25,
        "price": 2500
      }]
    }, {
      "name": "Обувь , Сумки не более 2 одинаковых",
      "max": " 10 ед/ пар",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 50
      }, {
        "from": 2,
        "to": 3,
        "price": 50
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 700
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }]
    }]
  },
  {
    "name": "Детские товары, сувениры и книги",
    "items": [{
      "name": "Игрушки   мелкие и малые до 2кг объема",
      "max": " 10 ед ",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 800
      }, {
        "from": 10,
        "to": 15,
        "price": 1200
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }]
    }, {
      "name": "Игрушки  средние, большие",
      "max": " до 4 ед ",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 800
      }, {
        "from": 10,
        "to": 15,
        "price": 1200
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2500
      }, {
        "from": 30,
        "to": 35,
        "price": 600
      }, {
        "from": 35,
        "to": 40,
        "price": 700
      }]
    }, {
      "name": "Коляски, кроватки, детские велосипеды",
      "max": " 1 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 800
      }, {
        "from": 10,
        "to": 15,
        "price": 1200
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2500
      }, {
        "from": 30,
        "to": 35,
        "price": 600
      }, {
        "from": 35,
        "to": 40,
        "price": 700
      }]
    }, {
      "name": "Книги и сувениры выпуска не старше 1957г в т.ч. Сувенирн посуда, картин изгот на производстве",
      "max": " 10 ед. ",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 800
      }, {
        "from": 10,
        "to": 15,
        "price": 1200
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2500
      }]
    }]
  },
  {
    "name": "Радиодетали",
    "items": [{
      "name": "Радиоуправляемые игрушки",
      "max": "1 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 300
      }, {
        "from": 1,
        "to": 2,
        "price": 600
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 1000
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 2000
      }, {
        "from": 10,
        "to": 15,
        "price": 1000
      }, {
        "from": 15,
        "to": 20,
        "price": 1500
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }]
    }, {
      "name": "Радиодетали",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 300
      }, {
        "from": 1,
        "to": 2,
        "price": 600
      }, {
        "from": 2,
        "to": 3,
        "price": 600
      }, {
        "from": 3,
        "to": 4,
        "price": 1000
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 2000
      }]
    }]
  },
  {
    "name": "Тысяча мелочей",
    "items": [{
      "name": "с 'орех' (Бижутерия,заколки,резинки, батарейки, лампочки и т.д.)",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 800
      }, {
        "from": 10,
        "to": 15,
        "price": 1200
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }]
    }, {
      "name": "с 'кулак' (Фонарики, одоразовые бритвы и т.д)",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 800
      }, {
        "from": 10,
        "to": 15,
        "price": 1200
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }, {
        "from": 20,
        "to": 25,
        "price": 3000
      }, {
        "from": 25,
        "to": 30,
        "price": 4000
      }]
    }, {
      "name": "Пряжа  и др нити",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 300
      }, {
        "from": 4,
        "to": 5,
        "price": 400
      }, {
        "from": 5,
        "to": 10,
        "price": 800
      }, {
        "from": 10,
        "to": 15,
        "price": 1200
      }, {
        "from": 15,
        "to": 20,
        "price": 1600
      }]
    }]
  },
  {
    "name": "Для ремонта",
    "items": [{
      "name": "натяжные потолки",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 500
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 1500
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }]
    }, {
      "name": "лаки,краски",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 500
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 1500
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }]
    }, {
      "name": "Сухие смеси",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 500
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 1500
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": 2000
      }, {
        "from": 35,
        "to": 40,
        "price": 2000
      }]
    }, {
      "name": "Подвесной потолок и его комлектующие и Наполное покрытие не в рулоне, а также Плитка и изделия  из камня и дерева",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 500
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 1500
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": 2000
      }, {
        "from": 35,
        "to": 40,
        "price": 2000
      }]
    }, {
      "name": "Оборудование сантехническое, электрическое",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 500
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 1500
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": 2000
      }, {
        "from": 35,
        "to": 40,
        "price": 2000
      }]
    }]
  },
  {
    "name": "Автотовары",
    "items": [{
      "name": "З/ч ",
      "max": "до 20 ед",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 150
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 250
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }]
    }, {
      "name": "Под видом авто з/ч любые металл изделия",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 150
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 250
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2500
      }, {
        "from": 30,
        "to": 35,
        "price": 800
      }, {
        "from": 35,
        "to": 40,
        "price": 800
      }]
    }, {
      "name": "Шины, диски в т.ч. б/у до R14",
      "max": "2ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 150
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 250
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2500
      }, {
        "from": 30,
        "to": 35,
        "price": 800
      }, {
        "from": 35,
        "to": 40,
        "price": 800
      }]
    }, {
      "name": "Шины, диски в т.ч. б/у до R16",
      "max": "2ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 150
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 250
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2500
      }, {
        "from": 30,
        "to": 35,
        "price": 800
      }, {
        "from": 35,
        "to": 40,
        "price": 800
      }]
    }, {
      "name": "Шины, диски в т.ч. б/у до R18",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 150
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 250
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2500
      }, {
        "from": 30,
        "to": 35,
        "price": 800
      }, {
        "from": 35,
        "to": 40,
        "price": 800
      }]
    }, {
      "name": "Автомасла и др ГСМ и жидк",
      "max": "ем до 10л",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 50
      }, {
        "from": 1,
        "to": 2,
        "price": 100
      }, {
        "from": 2,
        "to": 3,
        "price": 150
      }, {
        "from": 3,
        "to": 4,
        "price": 200
      }, {
        "from": 4,
        "to": 5,
        "price": 250
      }, {
        "from": 5,
        "to": 10,
        "price": 500
      }, {
        "from": 10,
        "to": 15,
        "price": 800
      }, {
        "from": 15,
        "to": 20,
        "price": 1000
      }, {
        "from": 20,
        "to": 25,
        "price": 2000
      }, {
        "from": 25,
        "to": 30,
        "price": 2500
      }]
    }]
  },
  {
    "name": "Электроинструменты",
    "items": [{
      "name": "Электро-косилки,резки, Ручн Циркулярка, Перфоратор",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 150
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 250
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1200
      }, {
        "from": 20,
        "to": 25,
        "price": 1500
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": 2500
      }, {
        "from": 35,
        "to": 40,
        "price": 3000
      }]
    }, {
      "name": "Болгарка,Дрель Шуруповерты,Рубанок ручн",
      "max": "2 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 150
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 250
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1200
      }, {
        "from": 20,
        "to": 25,
        "price": 1500
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": 2500
      }, {
        "from": 35,
        "to": 40,
        "price": 3000
      }]
    }, {
      "name": "Сборная любых электроинструменты в кол-ве не более по 1 ед. каждого",
      "max": "4 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 150
      }, {
        "from": 2,
        "to": 3,
        "price": 200
      }, {
        "from": 3,
        "to": 4,
        "price": 250
      }, {
        "from": 4,
        "to": 5,
        "price": 300
      }, {
        "from": 5,
        "to": 10,
        "price": 600
      }, {
        "from": 10,
        "to": 15,
        "price": 900
      }, {
        "from": 15,
        "to": 20,
        "price": 1200
      }, {
        "from": 20,
        "to": 25,
        "price": 1500
      }, {
        "from": 25,
        "to": 30,
        "price": 2000
      }, {
        "from": 30,
        "to": 35,
        "price": 2500
      }, {
        "from": 35,
        "to": 40,
        "price": 3000
      }]
    }]
  },
  {
    "name": "Бензооборудование",
    "items": [{
      "name": "Бензопила,бензо-косилка,бензо-кусторез в уп.",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 1000
      }, {
        "from": 1,
        "to": 2,
        "price": 1000
      }, {
        "from": 2,
        "to": 3,
        "price": 1000
      }, {
        "from": 3,
        "to": 4,
        "price": 1000
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }, {
        "from": 20,
        "to": 25,
        "price": 2500
      }, {
        "from": 25,
        "to": 30,
        "price": 3000
      }, {
        "from": 30,
        "to": 35,
        "price": 3500
      }, {
        "from": 35,
        "to": 40,
        "price": 4000
      }]
    }, {
      "name": "Бензо-генераторы до 3,5 квт",
      "max": "1 ед.",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 1000
      }, {
        "from": 1,
        "to": 2,
        "price": 1000
      }, {
        "from": 2,
        "to": 3,
        "price": 1000
      }, {
        "from": 3,
        "to": 4,
        "price": 1000
      }, {
        "from": 4,
        "to": 5,
        "price": 1000
      }, {
        "from": 5,
        "to": 10,
        "price": 1200
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }, {
        "from": 20,
        "to": 25,
        "price": 2500
      }, {
        "from": 25,
        "to": 30,
        "price": 3000
      }, {
        "from": 30,
        "to": 35,
        "price": 3500
      }, {
        "from": 35,
        "to": 40,
        "price": 4000
      }]
    }]
  },
  {
    "name": "Изделия сугубо личные",
    "items": [{
      "name": "Изделия и экипировка для охоты и туризма",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }, {
        "from": 5,
        "to": 10,
        "price": 1000
      }, {
        "from": 10,
        "to": 15,
        "price": 1500
      }, {
        "from": 15,
        "to": 20,
        "price": 2000
      }]
    }, {
      "name": "Изделия интимного назначения ",
      "max": "нет",
      "intervals": [{
        "from": 0,
        "to": 1,
        "price": 100
      }, {
        "from": 1,
        "to": 2,
        "price": 200
      }, {
        "from": 2,
        "to": 3,
        "price": 300
      }, {
        "from": 3,
        "to": 4,
        "price": 400
      }, {
        "from": 4,
        "to": 5,
        "price": 500
      }]
    }]
  },

];
