<option value="1">Горловка</option>
<option value="2">Донецк-1 (Юзовский Пассаж)</option>
<option value="3">Донецк-2 (Крытый рынок)</option>
<option value="4">Донецк-3 (Покровский рынок)</option>
<option value="16">Донецк-4 (Майский рынок)</option>
<option value="18">Донецк-5 (Текстильщик)</option>
<option value="12">Дебальцево</option>
<option value="5">Енакиево</option>
<option value="7">Макеевка-1 (Центр)</option>
<option value="8">Макеевка-2 (мкр-н Зеленый)</option>
<option value="9">Снежное</option>
<option value="10">Шахтерск</option>
<option value="11">Ясиноватая</option>
<option value="13">Алчевск</option>
<option value="14">Луганск-2 (Автовокзал)</option>
<option value="19">Луганск-3 (кв-л Молодежный)</option>
<option value="20">Луганск-4 (кв-л Ольховский)</option>
<option value="15">Стаханов</option>
